version: "3.8"

services:
  adonisjs:
    build: .
    container_name: adonis_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3333
      APP_KEY: your_app_key
      DB_CONNECTION: pg
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: adonis
      PG_PASSWORD: secret
      PG_DB_NAME: adonis_db
    volumes:
      - .:/app
      - /app/node_modules # Evita conflictos con las dependencias locales

  postgres:
    image: postgres:15
    container_name: adonis_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: